import random
random_integer1 = random.randint(1,50)
print("First Random Integer:",random_integer1)
random_integer2 = random.randint(1,50)
print("Second Random Integer:", random_integer2)
random_integer3 = random.randint(1,50)
print("Third Random Integer:", random_integer3)
random_integer4 = random.randint(1,50)
print("Fourth Random Integer:", random_integer4)
random_integer5 = random.randint(1,50)
print("Fifth Random Integer:", random_integer5)