color_list = ["Red","Blue","Green","White","Black"]
color_list.append("Orange")
print("After append: ",color_list)
color_list.insert(1,"Yellow")
print("After insert: ",color_list)
color_list.remove("Green")
print("After remove: ",color_list)
color_list.reverse()
print("After reverse: ",color_list)
color_list.sort()
print("After sort: ",color_list)
count = color_list.count("Red")
print("Count of Red: ",count)
index = color_list.index("White")
print("Index of White: ",index)